version: '2'

services:
  workspace:
    image: coursera-single-page-web-apps-with-angularjs:dev-workspace
    build: ./
    ports:
      - 3000:3000 # browser-sync
    volumes:
      - ./../../:/workspace
    command: tail -f /dev/null
    